apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: sunghoonshin/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS 
              value: "auth-service.default"